# Generated by Django 3.0.6 on 2020-05-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('group_project', models.BooleanField(blank=True, null=True)),
                ('picture_1', models.FilePathField(blank=True, null=True, path='projects/static/img', recursive=True)),
                ('picture_2', models.FilePathField(blank=True, null=True, path='projects/static/img', recursive=True)),
                ('picture_3', models.FilePathField(blank=True, null=True, path='projects/static/img', recursive=True)),
                ('picture_4', models.FilePathField(blank=True, null=True, path='projects/static/img', recursive=True)),
            ],
        ),
    ]
