# Generated by Django 3.0.7 on 2020-08-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture_1',
            field=models.FilePathField(blank=True, null=True, path='static/img/projects', recursive=True),
        ),
    ]
