# Generated by Django 3.0.7 on 2020-08-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200818_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture_2',
            field=models.FilePathField(blank=True, null=True, path='static/img/projects', recursive=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture_3',
            field=models.FilePathField(blank=True, null=True, path='static/img/projects', recursive=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture_4',
            field=models.FilePathField(blank=True, null=True, path='static/img/projects', recursive=True),
        ),
    ]
