# Generated by Django 3.0.6 on 2020-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200727_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('JS', 'JavaScript'), ('DJ', 'Django'), ('RR', 'React-Redux'), ('RE', 'React'), ('PY', 'Python')], max_length=2, null=True),
        ),
    ]
