# Generated by Django 3.0.6 on 2020-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
