# Generated by Django 3.1 on 2020-08-18 20:24

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('picture_1', models.FilePathField(blank=True, null=True, path='static/img/blog', recursive=True)),
                ('picture_2', models.FilePathField(blank=True, null=True, path='static/img/blog', recursive=True)),
                ('picture_3', models.FilePathField(blank=True, null=True, path='static/img/blog', recursive=True)),
                ('picture_4', models.FilePathField(blank=True, null=True, path='static/img/blog', recursive=True)),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
    ]
