# Generated by Django 3.1 on 2020-08-27 18:29

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('header_image_text', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture_1_text', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture_2_text', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture_3_text', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture_4_text', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
    ]
