# Generated by Django 3.1 on 2020-08-18 23:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_header_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[150, 150], upload_to='thumbnails/'),
        ),
    ]
