# Generated by Django 3.1 on 2020-08-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200818_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_thumbnail',
        ),
    ]
